### ISSUE TITLE
Scrambled program info

### ISSUE THREAD

**Issue by reiska123** [grinsted/plugin.video.telkkarista#5]
When pressing info button to show program info, only scrabled code shows up.

**Comment by grinsted** [comment]
Hi 

This is by choice. The problem is that in order to get the program info, then I needed to send a request to the server for every single program on the list. That is really slow, and the server will block the ip for making too many requests per second. They have updated the api so that you can request detailed  info for many programs with a single request, but it still triggers the ip block. So for the moment it simply does not fetch any detailed program info at all. Instead I use the field for debug info, which is what you see. 

You can try the other telkkarista plugin by rasjani here on github. It can fetch program info at a performance hit, but it caches the info which helps alot.

**Comment by reiska123** [comment]
Hello! Thank you very much for the plugin! The other plugin can somehow manage to get the info without ip blockage, I assume? I like your plugin better but it is impossible to know which episode is which when you see the search results. Or is there some workaround I'm not aware of? Cheers!

-Reko

**Comment by grinsted** [comment]
I am not aware of a workaround. - Except rasjanis approach. There he
introduces a delay between each epg/info call. But to me that introduces a
painful delay that I am not happy with.

It would be great if I could somehow inform kodi to only request the info
on demand, but that seems impossible. Atleast I have not been able to find
the infrastructure in kodi for doing so. One option I have considered was
to add a context menu item with "detailed program info" or something. When
you selected that, then you would be brought to a list with all the
different qualities available for that program. Here it would not be a
problem to fetch the info as there would just be a single program on that
list.

It would be even better if telkkarista changed their api so that you could
get the info. I'd also like if they could give a thumbnail (which they
don't have on their site). But I don't know how to contact telkkarista. But
if I could then I'd submit a few requests for some relatively minor api
changes like that.

Best
Aslak
